name: caterbid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^10.3.3 
  path: ^1.9.1

  # State Management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.1

  # Navigation & Routing
  go_router: ^14.1.4

  # UI Components
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.1
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1

  # Location
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  google_places_flutter: ^2.1.1

  # Internet Request
  http: ^1.2.0
  equatable: ^2.0.7
  http_parser: ^4.1.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

  # Storage
  flutter_secure_storage: 
  overlay_loader_with_app_icon: ^0.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
